### ISSUE TITLE
Voice-over accessibility crashes over labels with STUImageTextAttachment

### ISSUE THREAD

**Issue by Fabezi** [stephan-tolksdorf/STULabel#12]
Attached example project:
<img width="725" alt="Screenshot 2020-04-18 at 9 22 00" src="https://user-images.githubusercontent.com/3667836/79630095-39cb8b00-8157-11ea-8492-8eff06f45685.png">

[accessibility-crash.zip](https://github.com/stephan-tolksdorf/STULabel/files/4496165/accessibility-crash.zip)

**Comment by Fabezi** [comment]
Basically, if you do not provide stringRepresentation for STUImageTextAttachment(stringRepresentation: nil), STUTextFrameAccessibilityElement.mm:304 string range will be null and throws out of bounds
```
NSString* const language = [label attribute:UIAccessibilitySpeechAttributeLanguage atIndex:0 longestEffectiveRange:&effectiveRange inRange:NSRange{0, stringRange.length}];
-> Thread 1: Exception: "NSRLEArray objectAtIndex:effectiveRange:: Out of bounds"
```

**Comment by stephan-tolksdorf** [comment]
Thanks for the report and repro sample! Should be fixed now.
