### ISSUE TITLE
Reference to 'Byte' is ambiguous compiler error under Xcode 12

### ISSUE THREAD

**Issue by tkirby** [stephan-tolksdorf/STULabel#16]
Compiler error on Xcode 12:

Reference to 'Byte' is ambiguous

in 5 places.

Pods/STULabel/STULabel/Internal/TextStyle.hpp:432:59: Reference to 'Byte' is ambiguous
Pods/STULabel/STULabel/Internal/TextStyle.hpp:433:55: Reference to 'Byte' is ambiguous
Pods/STULabel/STULabel/Internal/TextStyle.hpp:327:71: Reference to 'Byte' is ambiguous
Pods/STULabel/STULabel/Internal/TextStyle.hpp:335:71: Reference to 'Byte' is ambiguous
Pods/STULabel/STULabel/Internal/TextStyle.hpp:448:50: Reference to 'Byte' is ambiguous

**Comment by barMapprosing** [comment]
I'm having the same issue!
I had to re-install some other pods and then this error disappeared, but now it has returned and glad I'm not the only one.

**Comment by barMapprosing** [comment]
@tkirby Looks like someone made a PR fixing it, but it wasn't approved yet.

**Comment by Zeeshan612** [comment]
@stephan-tolksdorf I am having same issue for Xcode 12, Kindly update soon as I need this fix ASAP. Thank you

**Comment by stephan-tolksdorf** [comment]
Please check whether version 0.8.7 resolves this issue for you.

**Comment by Zeeshan612** [comment]
Yes, Now it's working fine to me. Thank you for the quick update 😊
