### ISSUE TITLE
Declaration of 'atomic' must be imported from module 'std.atomic' before it is required

### ISSUE THREAD

**Issue by rakesh6932** [stephan-tolksdorf/STULabel#47]
I m not able to my code because it gives me an error "Declaration of 'atomic' must be imported from module 'std.atomic' before it is required"
X code version 13.3.1 
Pod "STULabelSwift', '~> 0.8.7'"
Min Deployment target 13.0
<img width="746" alt="Screenshot 2022-06-15 at 12 23 20 PM" src="https://user-images.githubusercontent.com/105790481/173761323-5a1a0260-071e-40bb-881c-1e2095129872.png">

**Comment by tkirby** [comment]
This PR fixes it

https://github.com/stephan-tolksdorf/STULabel/pull/45#issuecomment-1147240962

**Comment by stephan-tolksdorf** [comment]
Thanks for reporting this issue @rakesh6932 and thanks for fixing it @tkirby!
