### ISSUE TITLE
STULabelSuperlayerObserver -dealloc Race / Crash

### ISSUE THREAD

**Issue by b3ll** [stephan-tolksdorf/STULabel#7]
So I've been messing about with things a bunch recently, specifically using STULabel with both Texture (AsyncDisplayKit) and SwiftUI, and I've noticed there's a pretty wonky crash happening with the KVO stuff as part of `STULabelSuperlayerObserver`.

Basically, it's getting into a state where `STULabelLayer`'s `-dealloc` is being invoked, which is causing `STULabelSuperlayerObserver`'s `-dealloc` to be invoked, which'll crash since it's trying to remove observers on an object that's already been deallocated (rather than having the `STULabelSuperlayerObserver` explicitly torn down / removed beforehand). 

What's the purpose of `STULabelSuperlayerObserver` / does it need to be used?

I've been messing a bunch with this trying to fix it, and it seems to only happen once I present a View Controller (containing an STULabel wrapped in a ScrollView), and then later dismiss it. Changing the `_layer` to not be `__unsafe_unretained` mitigates the issue, but then also causes all `STULabel`s to never release lol

**Comment by b3ll** [comment]
imo STULabel manually invoking the removal of `STULabelSuperlayerObserver` as part of its dealloc seems safer, but I'm not entirely sure if that's cleaner

**Comment by b3ll** [comment]
huh, actually it looks like it has nothing to do with ASDK or SwiftUI for that matter… just a vanilla UIKit view controller holding a `STULabel` being presented manually / dismissed manually (without the view controller animation stuff) but still using the container view controller APIs causes it to crash…

**Comment by stephan-tolksdorf** [comment]
`LayerVisibleBoundsObserver` is used by the `STUTileLayer` to observe the visible area of the layer. If you can provide a repro example, I could take a look this weekend.

**Comment by b3ll** [comment]
Yeah, I figured that's sorta what it was used for… for simplicities sake, does observing the bounds of a scrollview (monitored by `-willMoveToSuperView` or something) work better than using KVO to tear down KVO? Still parsing through a lot of the code lol

I think Apple changed the way they unload views or layers or something recently, since I only noticed this with iOS 13 (I think)

Here's a sample that repros, in `ViewController.swift` it opens up a view controller (`STULabelTestViewController.swift`) and then dismisses it after 6s. It'll immediately crash every time

[TestSTULabel.zip](https://github.com/stephan-tolksdorf/STULabel/files/4073509/TestSTULabel.zip)

**Comment by stephan-tolksdorf** [comment]
This was indeed a bug. Thanks for reporting it! I think I've [fixed it](https://github.com/stephan-tolksdorf/STULabel/commit/f4a81eadc3d42ea78f449e023f4d3fab0339c277). Please try the new version.

**Comment by b3ll** [comment]
It works!! Thanks so much for fixing! :)
